# Generated by Django 5.2.7 on 2025-10-10 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('config', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.adcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label_en', models.CharField(max_length=120)),
                ('label_ar', models.CharField(blank=True, max_length=120, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('visible_public', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, null=True)),
                ('placeholder_en', models.CharField(blank=True, max_length=120, null=True)),
                ('placeholder_ar', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mainapp.adcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.fieldtype')),
            ],
            options={
                'ordering': ['order_index', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AdMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, max_length=5)),
                ('url', models.URLField(max_length=500)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='mainapp.ad')),
            ],
            options={
                'indexes': [models.Index(fields=['ad', 'kind', 'order_index'], name='mainapp_adm_ad_id_b471a3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'video')), fields=('ad',), name='unique_video_per_ad')],
            },
        ),
        migrations.CreateModel(
            name='AdFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mainapp.ad')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_values', to='mainapp.fielddefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['ad', 'field'], name='mainapp_adf_ad_id_5efd54_idx')],
                'unique_together': {('ad', 'field', 'locale')},
            },
        ),
    ]
