# Generated by Django 4.2.25 on 2025-10-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_adcategory_fieldtype_ad_fielddefinition_admedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('first_scan_at', models.DateTimeField(blank=True, null=True)),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code', to='mainapp.ad')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=12, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_logs', to='mainapp.ad')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mainapp.qrcode')),
            ],
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['batch'], name='mainapp_qrc_batch_71e456_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['is_assigned', 'is_activated'], name='mainapp_qrc_is_assi_8d5408_idx'),
        ),
    ]
