# Generated by Django 4.2.25 on 2025-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_carmake_qrcode_profile_email_profile_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
