"""
Django settings for AlMotori project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, '.env'))

ONESIGNAL_APP_ID = os.getenv("ONESIGNAL_APP_ID")
ONESIGNAL_API_KEY = os.getenv("ONESIGNAL_API_KEY")

if not ONESIGNAL_APP_ID or not ONESIGNAL_API_KEY:
    raise ValueError("❌ Missing OneSignal credentials in environment variables.")

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xh-_=4%%$#c5@vv+i-ad+57j##$lcrp%)!-l6aknp_h*4%-z-2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# python manage.py 
ALLOWED_HOSTS = ["motori.a.alce-qa.com", "www.motori.a.alce-qa.com","127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://motori.a.alce-qa.com",
    "https://www.motori.a.alce-qa.com",
]

# Application definition

INSTALLED_APPS = [
        "jazzmin",                # ← must be before django.contrib.admin

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        'rest_framework',
    'rest_framework.authtoken',
        'mainapp',   # 👈 add this

]

JAZZMIN_SETTINGS = {
    "site_title": "Al-Motori Admin",
    "site_header": "Al-Motori",
    "site_brand": "Al-Motori Dashboard",
    "welcome_sign": "Welcome to Al-Motori Admin",
    "copyright": "© 2025 Al-Motori",

    # ==== Icons for each model ====
    "icons": {
        "mainapp.Ad": "fas fa-car",
        "mainapp.Profile": "fas fa-user-circle",
        "mainapp.QRCode": "fas fa-qrcode",
        "mainapp.QRScanLog": "fas fa-history",
        "mainapp.Notification": "fas fa-bell",

        # Hidden from user but you can still style them
        "mainapp.FieldType": "fas fa-tag",
        "mainapp.FieldDefinition": "fas fa-list-alt",
    },

    # ==== App icons ====
    "icons": {
        "mainapp": "fas fa-folder-open",
    },

    # ==== Sidebar ====
    "show_sidebar": True,
    "navigation_expanded": True,

    # ==== Custom CSS if needed ====
    "custom_css": "admin/custom.css",

    # Sidebar menu ordering
    "order_with_respect_to": ["mainapp"],
}


JAZZMIN_SETTINGS.update({
    "custom_links": {
        "mainapp": [{
            "name": "Support",
            "url": "mailto:support@aialmotori.com",
            "icon": "fas fa-headset",
            "permissions": ["auth.view_user"]
        }],
    },
})

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",  # Themes: cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti.
    "navbar": "navbar-dark bg-primary",
    "sidebar": "sidebar-dark-primary",
    "footer_fixed": True,
}

#
EDITOR_MAX_ADS = 200     # per staff/editor user
EDITOR_MAX_IMAGES = 12  
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",   # simplest
        # Or use JWT later:
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "EXCEPTION_HANDLER": "mainapp.exception_handler.custom_exception_handler",

}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AlMotori.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AlMotori.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# 
# settings.py
import os

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "motori",
#         "USER": "mj",
#         "PASSWORD": "g100g100Aa$$",
#         "HOST": "localhost",  # or your DB server/VPS IP
#         "PORT": "3306",
#         "OPTIONS": {
#             "charset": "utf8mb4",
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1",
#         },
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "artlinew_Motori",
        "USER": "artlinew_Motori_Admin",
        "PASSWORD": "g100g100Aa$$",
        "HOST": "localhost",  # or your DB server/VPS IP
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JS, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
